<a href="https://colab.research.google.com/github/priyapatel1/d3/blob/main/SCS_3253_Group_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
fires_df = pd.read_csv("/content/drive/MyDrive/ML_Group_Project/data/fires_df.csv")

/content/drive/MyDrive/ML_Group_Project/data/fires_df.csv
/content/drive/MyDrive/ML_Group_Project/data/no_fires_df.csv

In [ ]:
fires_df

,Unnamed: 0,cell,ID.x,elevation,ID.y,SR_B3,ID.x.1,NBR.x,ID.y.1,NDMI,ID.x.2,NBR.y,ID.y.2,NDVI,ID.x.3,SR_B5,ID.y.3,SR_B4,ID.x.4,SR_B7,ID.y.4,SR_B6
0,1,2018.0,20,0,20,14378.076923,20,0.199563,20,0.142595,20,0.073842,20,0.251519,20,17243.179487,20,14132.897436,20,11505.923077,20,12400.692308
1,2,2019.0,20,0,20,14478.461538,20,0.202467,20,0.146416,20,0.075767,20,0.251899,20,17374.564103,20,14187.512821,20,11523.641026,20,12439.000000
2,3,2020.0,20,0,20,14550.717949,20,0.203500,20,0.149354,20,0.080366,20,0.200919,20,17373.333333,20,14252.923077,20,11498.025641,20,12385.923077
3,4,2021.0,20,0,20,14550.717949,20,0.203500,20,0.149354,20,0.080366,20,0.200919,20,17373.333333,20,14252.923077,20,11498.025641,20,12385.923077
4,5,2022.0,20,0,20,14636.820513,20,0.199142,20,0.143624,20,0.077757,20,0.177838,20,17403.205128,20,14342.025641,20,11622.897436,20,12524.820513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466418,466419,21753785.0,12,0,12,19800.102564,12,0.298436,12,0.241447,12,0.158531,12,0.064631,12,24324.333333,12,19693.743590,12,13142.794872,12,14381.282051
466419,466420,21753786.0,12,0,12,19800.102564,12,0.298436,12,0.241447,12,0.158531,12,0.064631,12,24324.333333,12,19693.743590,12,13142.794872,12,14381.282051
466420,466421,21753787.0,12,0,12,19973.230769,12,0.289868,12,0.231406,12,0.152503,12,0.088952,12,24342.717949,12,19909.846154,12,13401.794872,12,14687.384615
466421,466422,21753788.0,12,0,12,20694.820513,12,0.291022,12,0.230966,12,0.166911,12,0.051570,12,24645.589744,12,20640.307692,12,13534.384615,12,14774.589744
466422,466423,21753789.0,12,0,12,20694.820513,12,0.291022,12,0.230966,12,0.166911,12,0.051570,12,24645.589744,12,20640.307692,12,13534.384615,12,14774.589744

In [ ]:
fires_df.describe()

,Unnamed: 0,cell,ID.x,elevation,ID.y,SR_B3,ID.x.1,NBR.x,ID.y.1,NDMI,ID.x.2,NBR.y,ID.y.2,NDVI,ID.x.3,SR_B5,ID.y.3,SR_B4,ID.x.4,SR_B7,ID.y.4,SR_B6
count,466423.000000,4.664230e+05,466423.000000,466423.0,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000,466423.000000
mean,233212.000000,8.830060e+06,45.856285,0.0,45.856285,21152.645166,45.856285,0.263016,45.856285,0.199154,45.856285,0.173502,45.856285,0.111741,45.856285,23631.199887,45.856285,21029.330142,45.856285,13750.322108,45.856285,14828.377618
std,134644.866641,6.107345e+06,66.790397,0.0,66.790397,2644.874453,66.790397,0.027149,66.790397,0.031238,66.790397,0.034950,66.790397,0.079357,66.790397,2349.728416,66.790397,2690.910178,66.790397,990.328783,66.790397,1249.721977
min,1.000000,2.018000e+03,12.000000,0.0,12.000000,14075.282051,12.000000,0.109267,12.000000,0.036760,12.000000,0.032631,12.000000,-0.131098,12.000000,16486.435897,12.000000,13895.230769,12.000000,10825.846154,12.000000,11272.307692
25%,116606.500000,5.731374e+06,24.000000,0.0,24.000000,19478.168691,24.000000,0.248485,24.000000,0.181937,24.000000,0.149474,24.000000,0.049010,24.000000,22157.105263,24.000000,19296.294872,24.000000,13033.789474,24.000000,13926.263158
50%,233212.000000,7.334886e+06,38.000000,0.0,38.000000,20964.368421,38.000000,0.264046,38.000000,0.198829,38.000000,0.174773,38.000000,0.103434,38.000000,23526.684211,38.000000,20837.153846,38.000000,13706.179487,38.000000,14766.105263
75%,349817.500000,9.409132e+06,38.000000,0.0,38.000000,22722.105263,38.000000,0.279272,38.000000,0.216915,38.000000,0.194287,38.000000,0.165152,38.000000,25094.973684,38.000000,22626.472222,38.000000,14432.358974,38.000000,15683.631579
max,466423.000000,2.175379e+07,394.000000,0.0,394.000000,34065.384615,394.000000,0.379650,394.000000,0.330561,394.000000,0.347341,394.000000,0.433172,394.000000,36011.794872,394.000000,34143.410256,394.000000,19416.750000,394.000000,21196.826087

In [ ]:
no_fires_df = pd.read_csv("/content/drive/MyDrive/data/no_fires_df.csv")

FileNotFoundError: ignored